model:
  _target_: learn.models.LinearModel
  params:
    training:
      solver: None
      ensemble: false
      cluster: 2000
    optimizer: None
    datahandler:
      class: learn.utils.nn.ModelDataHandler
      params:
        X:
          class: sklearn.preprocessing.StandardScaler
#          params:
        U:
          class: sklearn.preprocessing.MinMaxScaler
          params:
            feature_range: [-1.,1.]
        dX:
          class: sklearn.preprocessing.MinMaxScaler
          params:
            feature_range: [-1.,1.]
        sine_expand: []
