model:
  _target_: learn.models.GeneralNN
  class: learn.models.GeneralNN
  params:
    training:
      ensemble: false
      dx: ${env.params.dx}
      du: ${env.params.du}
      dt: ${env.params.dt}
      hid_width: 250
      hid_depth: 2
      probl: false #true
      activ: learn.utils.nn.Swish
      dropout: 0
      split: false
      mode: delta
      plot_loss: true
      cluster: 0
    optimizer:
      epochs:  12 #12
      batch: 32 # 200 #18
      split: .8
      lr: .0025
      lr_schedule: [30,6]
      preprocess: true
      verbose: false
    datahandler:
      class: learn.utils.nn.ModelDataHandler
      params:
        X:
          class: sklearn.preprocessing.StandardScaler
          #          params:
          U:
            class: sklearn.preprocessing.MinMaxScaler
            params:
              feature_range: [-1.,1.]
          dX:
            class: sklearn.preprocessing.MinMaxScaler
            params:
              feature_range: [-1.,1.]
          sine_expand: []
