defaults:
  - robot: ???
  - models: nn-e

save: true
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: /checkpoint/${env:USER}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

load:
  delta_state: true
  include_tplus1: True             # when true, will include the time plus one in the dataframe (for trying predictions of true state vs delta)
  trim_high_vbat: 4050             # trims high vbat because these points the quad is not moving
  takeoff_points: 180              # If not trimming data with fast log, need another way to get rid of repeated 0s
  trim_0_dX: True                  # if all the euler angles (floats) don't change, it is not realistic data
  find_move: True
  trime_large_dX: False             # if the states change by a large amount, not realistic
  bound_inputs: [1,65500]      # Anything out of here is erroneous anyways. Can be used to focus training
  stack_states: 3                  # IMPORTANT ONE: stacks the past states and inputs to pass into network
  collision_flag: False            # looks for sharp changes to tthrow out items post collision
  shuffle_here: False              # shuffle pre training, makes it hard to plot trajectories
  timestep_flags: []               # if you want to filter rostime stamps, do it here
  battery: True                   # if battery voltage is in the state data
  terminals: True                 # adds a column to the dataframe tracking end of trajectories
  fastLog: True                   # if using the software with the new fast log
  contFreq: 1                     # Number of times the control freq you will be using is faster than that at data logging
  iono_data: True
  zero_yaw: True
  moving_avg: 0
  base_dir: video-setup/
